name: Compile and Publish

on:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Nuget
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: '5.x'

    - name: Setup MSBuild
      id: setup_msbuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore dependencies
      run: nuget restore

    - name: Build
      run: msbuild unp4k.sln /m /verbosity:minimal /p:Configuration=Release
      
    - name: Package
      shell: cmd
      run: |
        cd src
        copy unp4k\bin\Release\net47\win-x64\unp4k.exe unp4k.gui\bin\Release\unp4k.exe
        erase *.pdb /s
        erase *.exe.config /s
        erase *.xml /s
        erase System.Net.Http.dll /s
        erase System.Runtime.dll /s
        erase System.IO.dll /s
        erase System.Security.*.dll /s

    - id: next_version
      name: Get next version
      uses: zwaldowski/semver-release-action@v1
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        bump: patch
        dry_run: true

    - uses: actions/upload-artifact@v2
      with:
        name: unp4k-suite-v${{ steps.next_version.outputs.version }}
        path: src/unp4k.gui/bin/Release

    - uses: actions/upload-artifact@v2
      with:
        name: unforge-v${{ steps.next_version.outputs.version }}
        path: src/unforge/bin/Release/net47/win-x64

    - uses: actions/upload-artifact@v2
      with:
        name: unp4k-v${{ steps.next_version.outputs.version }}
        path: src/unp4k/bin/Release/net47/win-x64
