name: Compile and Publish

on:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        
    - name: 'Get next minor version'
      id: semvers
      uses: "WyriHaximus/github-action-next-semvers@v1"
      with:
        version: ${{ steps.previoustag.outputs.tag }}

    - name: Determine Version
      id:   gitversion
      uses: gittools/actions/gitversion/execute@v0.9.7

    - name: Setup Nuget
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: '5.x'

    - name: Setup MSBuild
      id: setup_msbuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore dependencies
      run: nuget restore

    - name: Build
      run: |
        msbuild unp4k.sln /m /verbosity:minimal /p:Configuration=Release
        cd src
        copy unp4k\bin\Release\net47\win-x64\unp4k.exe unp4k.gui\bin\Release\unp4k.exe
        erase *.pdb /s
        erase *.exe.config /s
        erase *.xml /s
        erase System.Net.Http.dll /s
        erase System.Runtime.dll /s
        erase System.IO.dll /s
        erase System.Security.*.dll /s

    - uses: actions/upload-artifact@v2
      with:
        name: unp4k-suite-v${{ steps.semvers.outputs.patch }}
        path: src/unp4k.gui/bin/Release

    - uses: actions/upload-artifact@v2
      with:
        name: unforge-v${{ steps.semvers.outputs.patch }}
        path: src/unforge/bin/Release/net47/win-x64

    - uses: actions/upload-artifact@v2
      with:
        name: unp4k-v${{ steps.semvers.outputs.patch }}
        path: src/unp4k/bin/Release/net47/win-x64
